[project]
name = "owl"
version = "0.29.0"
description = "Package and project manager for the Mire (Avenys) language"
entry = "code/main.mire"

[build]
compiler = "mire"
profile = "debug"
opt-level = "0"

[paths]
sources = "code"
tests = "tests"
output = "bin"
cache = "bin/.cache"

[dependencies]
kioto = { path = "../kioto" }
testlib = { path = "./tests/lib" }
crypto = { path = "./code/crypto" }
