[project]
name = "owl"
version = "1.2.3"
description = "Package and project manager for the Mire (Avenys) language"
entry = "code/main.mire"

[build]
compiler = "mire"
profile = "debug"
opt-level = "0"
artifact = "bin"
runtime = "minimal"
target = "x86_64-unknown-linux-gnu"
panic = "abort"
incremental = true
debug-info = true

[paths]
sources = "code"
tests = "tests"
output = "bin"
cache = "bin/.cache"
generated = "bin/generated"

[cfg]
publisher = "publish.toml"
registry = "local"
registry_url = "http://localhost:8080"
cache = "~/.owl/cache"
libs = "~/.owl/libs"

[exports]
owl = "code/main.mire"
util = "code/util"
crypto = "code/crypto"
trust = "code/trust"
registry = "code/registry"
install = "code/install"
build = "code/build"
check = "code/check"
info = "code/info"
ui = "code/ui"
args = "code/args"
deps = "code/deps"
dep_resolver = "code/dep_resolver"
lockfile = "code/lockfile"
gc = "code/gc"
profile = "code/profile"
export = "code/export"
upgrade = "code/upgrade"
_externs = "code/_externs"

[dependencies]
mire = { path = "~/.owl/libs/mire" }
kioto = { path = "~/.owl/libs/kioto" }
testlib = { path = "~/.owl/libs/testlib" }
crypto = { path = "./code/crypto" }

[c]
sources = ["native/archive.c"]
libs = ["archive", "zstd"]

["owl@lock"]
version = "3"
